Repository sensu/sensu-ansible, pull requests merged in 2019-02, with the labels that each got.

#201 Bump minimum Ansible to 2.4
  README.md
  docs/index.md
  meta/main.yml
Labels: breaking

#202 Bump Inspec to 3.6.6
  molecule/shared/verify.yml
Labels: enhancement

#207 fix(group) rabbitmq_servers in default was not updated to new namespace.
  defaults/main.yml
Labels: bug

#209 Fixes loop issue #208
  docs/dynamic_checks.md
  tasks/plugins.yml
Labels: bug
